### ISSUE TITLE
Questão - Html estranho na página experiencia

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#11]
No html está como se tivesse um controle de tabs aqui, porém só tem um elemento com valor e no navegador, não existe.
Deveria conter mesmo ou esse html está sobrando?
![ebfjghkplkgomhfm](https://user-images.githubusercontent.com/5928832/130678001-61037a00-cabb-47d1-82a8-5a7bba7a5fcb.png)

Na tela não tem indicação visual que isso seria tabs:
![hgijhdanjknfdohb](https://user-images.githubusercontent.com/5928832/130678058-99b36f45-4573-465b-be1d-e9958acc9a45.png)

**Comment by pablo-ardito** [comment]
Corrigido

**Comment by pablo-ardito** [comment]
Confere por favor
