### ISSUE TITLE
Questão - Âncora dentro de âncora na página experiencia

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#12]
A ancora de fora não deveria ser uma div por exemplo? já que a de dentro é que realmente tem a url.
![fjggopkphfbhdpcl](https://user-images.githubusercontent.com/5928832/130678172-7d4b1f94-3484-4474-a28f-e47976325e87.png)

**Comment by pablo-ardito** [comment]
Enviado!

**Comment by pablo-ardito** [comment]
Confere se deu certo!
