### ISSUE TITLE
Todo - Layout do modal na página de busca, caso ocorra algum erro ao tentar reservar o produto.

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#19]

**Comment by pablo-ardito** [comment]
@cabralRodrigo montei o loader , veja se consegue aplicar na estrutura ou se precisa de algo mais:
https://codepen.io/pabloardito/pen/XWemVdb

**Comment by cabralRodrigo** [comment]
Como falamos via whatsapp, usaremos esse overlay somente para o carregamento. Então ainda precisamos de uma forma de mostrar ao usuário um erro que possa ocorrer

**Comment by pablo-ardito** [comment]
defini um modelo de modal com mensagem, é possível trocar os ícones usando as classes e também o conteúdo: busca-erro.php
