### ISSUE TITLE
Questão - Alterar controle de range de preço

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#25]
Estou utilizando react para implementar a página de busca.
Teria como trocar o controle de range para esse controle: [react-range](https://github.com/tajo/react-range)?

Somente o que eu preciso é o css. Um exemplo muito perto do que temos hoje, é esse: [https://react-range.netlify.app/?story=range--two-thumbs](https://react-range.netlify.app/?story=range--two-thumbs)

Teriamos como implementar essa mudança?

**Comment by helena-antidesign** [comment]
Dá uma olhada se resolve o que você precisa!
https://codesandbox.io/s/react-range-forked-yrhpn?file=/src/index.js

**Comment by cabralRodrigo** [comment]
Sim @helena-antidesign , isso resolveria. Ficando de acordo com o padrão visual que vcs desenvolveram para a journeys, pra mim está ótimo.
Desse forma posso interagir com esse filtro dentro da aplicação.

**Comment by pablo-ardito** [comment]
@cabralRodrigo usei o HTML do https://react-range.netlify.app/?story=range--two-thumbs o css ja está configurado, veja se precisa de algo mais

**Comment by cabralRodrigo** [comment]
Consegui integrar o html. Fechando.
