### ISSUE TITLE
Todo - Configuração interna para reservas do estoque da journeys

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#34]
Hoje, quando a reserva é negociada com diretamente com a journeys e um operador vai fazer essa reserva no sistema, ele tem disponível essas duas opções: 'publico' e 'interno'.
Temos que implementar isso na busca.
![image](https://user-images.githubusercontent.com/5928832/130908094-c8f966de-eca6-45e7-8dc4-172f585c169a.png)

**Comment by pablo-ardito** [comment]
Criado no arquivo /includes/hotel.php

**Comment by cabralRodrigo** [comment]
Fechado
