### ISSUE TITLE
Todo - Banner LGPD

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#4]

**Comment by pablo-ardito** [comment]
Sabe como será o modelo? com link para algum conteúdo, com "aceite", etc...

**Comment by cabralRodrigo** [comment]
Hoje é assim. esse link vai para uma página com os detalhes.
![image](https://user-images.githubusercontent.com/5928832/146373787-44cb92ce-f9b8-4da7-a325-8d5ad99570f0.png)

**Comment by pablo-ardito** [comment]
Está incluído nesta página: /busca-erro.php com display NONE, pesquise por: o-banner-lgpd
