### ISSUE TITLE
Todo - Overlay de carregamendo na tela de 'reservas.php'

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#48]
Seria bom termos uma overlay de carregamento para a lista de reservas.
Dependendo dos filtros que o usuário utilizar, podemos ter uma demora de até 8 segundos até os dados serem carregados.

**Comment by pablo-ardito** [comment]
podemos usar este padrão para os carregamentos: https://codepen.io/pabloardito/pen/XWemVdb

**Comment by cabralRodrigo** [comment]
Aguardo a inclusão no sass

**Comment by pablo-ardito** [comment]
Incluí no sass

**Comment by pablo-ardito** [comment]
exemplo: busca-vazia.php

**Comment by cabralRodrigo** [comment]
Implementado no projeto.
