### ISSUE TITLE
Bug - Versão do css do swiper diferente da versão do script.

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#49]
A versão do javascript do swiper é 6.5.9.
Porém ao importar o css com a url `https://unpkg.com/swiper/swiper-bundle.min.css` na verdade está importando a versão 7.0.8 pela url `https://unpkg.com/swiper@7.0.8/swiper-bundle.min.css`.

Já no front, tanto o script, quando o css está na versão 6.5.9.
E acaba acontecendo esse bug visual:
![image](https://user-images.githubusercontent.com/5928832/136867133-c777939f-3f42-4559-8109-4c7aea0e0a29.png)

Teriamos como passar a utilizar 7.0.8 tanto no javascript, tanto no css?

**Comment by pablo-ardito** [comment]
Corrigido

**Comment by pablo-ardito** [comment]
Verifica este item por favor

**Comment by cabralRodrigo** [comment]
corrigido
