### ISSUE TITLE
Todo - Criar estilos para as tags <select> da página 'busca.php'.

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#50]
![image](https://user-images.githubusercontent.com/5928832/143301203-c35382fb-ff7e-4191-a115-0db47e2618d6.png)

**Comment by pablo-ardito** [comment]
ajustado, por enquanto apenas removi o select-2 depois farei o novo estilo

**Comment by cabralRodrigo** [comment]
Mudei o título

**Comment by pablo-ardito** [comment]
O select já está com o estilo correto, as opções não precisam ter estilo, vamos manter assim por enquanto.
