### ISSUE TITLE
Bug - Erro no modal de reservar na página de busca

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#52]
Quando o usuári tenta reservar multiplas acomodações ao mesmo tempo, o layout não faz muito sentido.
Pq a tarifa "Twin Standart BB | Sem Reembolso" seria somente para uma das acomodações.
Como vamos mostrar mais de uma? não seria abaixo disso nos detalhes da habilitação?
![image](https://user-images.githubusercontent.com/5928832/144783832-dcc3f8d6-1abb-46fe-893a-f022bc31d172.png)

**Comment by pablo-ardito** [comment]
Ajustado

**Comment by cabralRodrigo** [comment]
Fechado
