### ISSUE TITLE
Bug - Informações do File na busca

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#53]
Os os campos 'File/Referência', 'Idioma', 'Pais' e 'Agrupamento' são do file (grupo de bookings) e não de cada booking.
como o layout está hoje, esses campos seriam repetidos para cada booking... pois estão debaixo da acomodação.
teriamos que jogar esses campos para cima, ou para o resumo na esquerda.
(lembrando que somentos os usuários internos tem acesso ao 'agrupamento', então devem existir a possibilidade de esconder esse elemento)
![image](https://user-images.githubusercontent.com/5928832/144790563-47f17f38-5c5e-4e2f-8510-4d28a0bda392.png)

**Comment by pablo-ardito** [comment]
Ajustado nos arquivo de reserva.php

**Comment by cabralRodrigo** [comment]
Fechado
