### ISSUE TITLE
Questão - O que vamos colocar no lugar de 'Habitação...' nos outros produtos (transfer por exemplo)

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#54]
![image](https://user-images.githubusercontent.com/5928832/144848490-65f2cf8e-b53d-4492-b0ca-2965e5d3b3a2.png)

**Comment by pablo-ardito** [comment]
@cabralRodrigo criei o arquivo busca-transfer.php para abrir o reserva-transfer.php que é um modelo diferente do reserva.php

**Comment by cabralRodrigo** [comment]
Achei aqui, o problema é que na esquerda ainda informações do hotel.
Imagino que vamos tirar, mas vamos colocar alguma coisa no lugar?
![image](https://user-images.githubusercontent.com/5928832/146260843-447617f1-3c27-4c9d-a951-1ff78962e5ad.png)

**Comment by pablo-ardito** [comment]
Ajustado, removi da área da direita e ficou no lugar do nome do Hotel

**Comment by cabralRodrigo** [comment]
Obrigado pelo ajustei, acabei colocando a tarifa que o usuário selecionou como título no lado esquerdo.
Acho que ficou bom.

![image](https://user-images.githubusercontent.com/5928832/148808739-ee917557-efd5-4feb-82f6-462936a7619e.png)
