### ISSUE TITLE
Questão - reserva.php - Como salvar valores?

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#58]
Os campos abaixo são editaveis.
Como vocês pensaram o salvamento das alterações?
O sistema vai salvar automáticamente ou deveria aparecer um botão de salvar quando o usuário alterar algo?
![image](https://user-images.githubusercontent.com/5928832/148632131-fab222d6-32e8-4177-8ee9-d282e1089954.png)

**Comment by pablo-ardito** [comment]
Desenvolvendo...
