### ISSUE TITLE
Bug - reserva.php - Tela do doc digital, invoice e voucher estão quebradas

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#61]
![image](https://user-images.githubusercontent.com/5928832/148952992-a82e63a1-2ffa-403d-ae20-9ebe5bd86872.png)
![image](https://user-images.githubusercontent.com/5928832/148953014-8a46e8c6-cbb7-4d49-88ea-40f868dd8239.png)
![image](https://user-images.githubusercontent.com/5928832/148953035-683d9572-9103-439e-b5da-45965fda48db.png)

**Comment by pablo-ardito** [comment]
Corrigidas
