### ISSUE TITLE
TODO - reserva.php - Criar modal de alteração de politica de cancelamento

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#63]
![image](https://user-images.githubusercontent.com/5928832/148953759-ef853fe3-a591-4439-8919-39dc16e4400d.png)

Seria mais um botão no booking:
![image](https://user-images.githubusercontent.com/5928832/148953837-8ac585b5-f6f7-4147-bdc8-a97eea337538.png)

**Comment by pablo-ardito** [comment]
Criado
