### ISSUE TITLE
TODO - reserva.php - Criar botão de confirma reserva

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#65]
Hoje não temos nenhum modal.
Quando o usuário clica nesse botão, ele somente abre um alert.
Se achar melhor, podemos fazer um modal.

![image](https://user-images.githubusercontent.com/5928832/148954102-140649eb-3ac4-45b1-a609-c8ea743d05ef.png)

**Comment by pablo-ardito** [comment]
Botão criado (atualizei o arquivo da fonte dos ícones)
