### ISSUE TITLE
TODO - busca.php - Adicionar estilos para campos que falharam a validação

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#67]
![image](https://user-images.githubusercontent.com/5928832/148954892-e4ca4dbc-b3bf-4786-9835-8058b90f139e.png)

**Comment by pablo-ardito** [comment]
Recomendo usarmos a validação do bootstrap: https://getbootstrap.com.br/docs/4.1/components/forms/
Qualquer dúvida me avise!
