### ISSUE TITLE
TODO - reserva.php - Criar modal de edição de fornecedor

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#68]
![image](https://user-images.githubusercontent.com/5928832/148955698-798a9f2d-eb13-4de3-8539-042f2e6f4943.png)
![image](https://user-images.githubusercontent.com/5928832/148955700-8a87f9f1-0bdd-4c4a-a81b-dc87e89d6018.png)

**Comment by pablo-ardito** [comment]
Modal e ícone criado
