### ISSUE TITLE
TODO - reserva.php - Criar modal de excluir todos reservas selecionadas

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#69]
![image](https://user-images.githubusercontent.com/5928832/148955984-fb347e89-c546-4812-9522-221dbecad07d.png)

**Comment by pablo-ardito** [comment]
@cabralRodrigo esse modal tem alguma informação de confirmação? tem um print de como é hoje?

**Comment by cabralRodrigo** [comment]
![image](https://user-images.githubusercontent.com/5928832/151033625-961a857d-3400-49a2-bf48-dbda671fbaaa.png)

Esse é o modal de cancelamento do sistema.
Quando o usuário utiliza o botão de 'excluir todas', só adicionamos mais itens na lista de reservas sendo cancelada.

Uma observação importante é: quando o usuário abre o modal deve aparecer uma mensagem de carregando
![image](https://user-images.githubusercontent.com/5928832/151033799-918ae691-51bc-488f-ada5-13cd4ca8c784.png)

Após o cancelamento, o sistema muda cada linha de cada booking mostrando se o cancelamento foi feito com sucesso.
