### ISSUE TITLE
TODO - reserva.php - Criar modal para log de alterações do FILE

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#70]
Assim como o booking tem um log de alterações, o file também tem.
Devemos criar esse modal.
![image](https://user-images.githubusercontent.com/5928832/148956110-eb9f36c2-4347-49b2-90ca-a7089c534277.png)

**Comment by pablo-ardito** [comment]
Já desenvolvemos, quando clica nele, abre o modal, só está abrindo na aba errada, segue prin
![Captura de Tela 2022-01-17 às 15 25 30](https://user-images.githubusercontent.com/45012012/149821496-05956fd8-f670-417a-8348-ced7eae828e0.png)
t
