### ISSUE TITLE
TODO - reserva.php - Criar modal de reversão do cancelamento

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#71]
![image](https://user-images.githubusercontent.com/5928832/148956963-f5db792b-2c68-4f51-88c9-2449ae5d03c5.png)
![image](https://user-images.githubusercontent.com/5928832/148956996-2dcbd2cb-bbde-4e9d-ba9a-96a63d3af27a.png)

**Comment by pablo-ardito** [comment]
Criado
