### ISSUE TITLE
TODO - reserva.php - Alteração no modal do voucher para múltiplos bookings

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#73]
Repare que hoje temos a opção de emitir o voucher para múltiplos bookings de uma vez.
Assim o modal deve ter o layout para a identificação de cada booking selecionado e seus respectivos campos.
![image](https://user-images.githubusercontent.com/5928832/148957605-9ec1be21-fa97-49d5-8da6-8f043422e35a.png)
![image](https://user-images.githubusercontent.com/5928832/148957615-cfc13d66-ebf4-49ad-81cf-ad7d9de78d25.png)
![image](https://user-images.githubusercontent.com/5928832/148957884-80c53ecb-be88-4ec2-ba00-babc29d6f847.png)

**Comment by pablo-ardito** [comment]
Corrigido
