### ISSUE TITLE
2874 - Novo Layout > adicionar a frase de chd para transfer e tour

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#79]
Adicioncar a frase para os serviços de transfer e tour
![image](https://user-images.githubusercontent.com/5928832/173583358-b7231fe1-09d3-400d-bdf8-903b8b5a4029.png)

O ideal seria abrir uma tela com essa informação quando a pessoa fosse selecionar a quantidade de passageiros para o serviço

![image](https://user-images.githubusercontent.com/5928832/173583381-108a90c0-0fa4-4273-a950-054a11540711.png)

**Comment by pablo-ardito** [comment]
Feito! acho que resolveu bem
