### ISSUE TITLE
2872 - Novo Layout > botão limpar filtros

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#80]
Falta o botão limpar filtros

![image](https://user-images.githubusercontent.com/5928832/173583690-1fdf8dad-7111-4cbf-ae0b-226c97aa44f7.png)

Novo layout - falta botão

![image](https://user-images.githubusercontent.com/5928832/173583700-01c605ee-762a-480b-a4d8-e641625f92ed.png)

**Comment by pablo-ardito** [comment]
Feito!
