### ISSUE TITLE
2867 - NOVO LAY OUT - BOTÃO RETORNAR

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#81]
Veja aqui no print. Abaixo, estamos na etapa onde é possível adicionar mais bookings em file já criado...
 

Precisamos também, que exista o botão “Retornar” na etapa abaixo, assim como existe no atual, para retorne ao tripplaner para criação de um novo FILE.
 

![image](https://user-images.githubusercontent.com/5928832/173584347-367292a0-a554-42b2-a629-b581b3d476af.png)

  b. Precisamos também, que exista o botão “Retornar” na etapa abaixo, assim como existe no atual, para retorne ao tripplaner para criação de um novo FILE

![image](https://user-images.githubusercontent.com/5928832/173584362-1ab1e309-a1ee-4d98-9194-dbd0812f3692.png)

**Comment by pablo-ardito** [comment]
Resolvemos com o header fixo
