### ISSUE TITLE
2846 - Novo layout > ficha tecnica de hotéis

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#83]
Os campos de classificação estão sem os links

![image](https://user-images.githubusercontent.com/5928832/173585210-233db6fe-918d-4009-986e-0277d23c2f15.png)

![image](https://user-images.githubusercontent.com/5928832/173585222-90e7a3b3-0692-4bd3-91f9-9b53d90551e2.png)

**Comment by pablo-ardito** [comment]
Finalizei, vou subir no git e te aviso!
