### ISSUE TITLE
2844 - Novo layout > tarifário hotéis

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#84]
Alterar ordem do nome do hotel e endereço para que fique igual ao da ficha técnica, saindo primeiro o nome do hotel, logo abaixo a categoria e depois o endereço
A fonte e cor, manter

TE

![image](https://user-images.githubusercontent.com/5928832/173585482-8626c7d4-0514-4067-a426-6ada3c1276de.png)

FICHA TECNICA

![image](https://user-images.githubusercontent.com/5928832/173585502-f1e26e49-d065-4829-919f-729f02aac963.png)

**Comment by pablo-ardito** [comment]
Feito em tarifarios, sem as estrelas

**Comment by cabralRodrigo** [comment]
@pablo-ardito vi que você aplicou esse estilo para o nome da região. 
Precisamos no nome do produto:
![image](https://user-images.githubusercontent.com/5928832/173982819-c4f3e808-da54-436f-89ed-158404842071.png)

Onde vc alterou pode ficar como estava.
O que eles querem é o nome produto em verde mas com o endereço abaixo e com as estrelas.

**Comment by pablo-ardito** [comment]
Não entendi! rsss qual é o nome do produto?

**Comment by pablo-ardito** [comment]
Rodrigo, já atualizei com as estrelas, se não utilizar ela, pode remover da tag H2 (aviso quando subir no git)

**Comment by cabralRodrigo** [comment]
ja corrigido.
