### ISSUE TITLE
Todo - Paginação na home logada

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#86]
Tentei colocar a paginação na home logada também (copiando da home) e ficou assim. Poderia ajustar?

![image](https://user-images.githubusercontent.com/5928832/173702856-038254ca-66a4-46da-b547-fa666ebc8ed2.png)

Meu HTML está assim:
![image](https://user-images.githubusercontent.com/5928832/173703020-72b36da1-7fd8-4cba-b2a9-09fab7055a71.png)

**Comment by pablo-ardito** [comment]
Corrigido!
