### ISSUE TITLE
2880 - NOVO LAYOUT - COMENTÁRIOS INTERNOS

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#89]
Assim como existe no Lay out atual, precisamos que fique visivelmente informado se há comentários internos inseridos.

![image](https://user-images.githubusercontent.com/5928832/173716901-59c8169b-0da9-4d8e-b891-2f7e1459dd46.png)
![image](https://user-images.githubusercontent.com/5928832/173716922-e4c1a395-a46e-462e-9a23-d5e3aefaa1e6.png)

**Comment by pablo-ardito** [comment]
Feito!
