### ISSUE TITLE
Bug - Seletores utilizando ids quebram o layout

### ISSUE THREAD

**Issue by cabralRodrigo** [cabralRodrigo/antidesign#94]
Nesse modal do reserva.php existem alguns estilos utilizando diretamente ids.
Poderia passar a usar somente classes?
Como não estamos utilizando os mesmos ids, a página acaba ficando assim:
![image](https://user-images.githubusercontent.com/5928832/174500591-43633439-f389-4c62-9e9f-2dde1f08a5a3.png)

Exemplos:
![image](https://user-images.githubusercontent.com/5928832/174500595-c86a43e1-cd11-42e1-b63b-38e737030ee3.png)
![image](https://user-images.githubusercontent.com/5928832/174500598-92f08ac7-0377-4d3b-a0f7-f89f16c171ce.png)
![image](https://user-images.githubusercontent.com/5928832/174500600-83237a88-8f95-4cf5-b983-edf60d3131f8.png)

**Comment by pablo-ardito** [comment]
Corrigido no CSS, enviado como BUGS
